resolution: "1K"      # (1K, 2K, 4K, 8K)
file_type: "JPG"      # (JPG/PNG)
unzip: 
  enabled: true       # (true/false)
  folder: "unzipped"
keep_files:           # Files marked as false will be deleted
  color: true
  roughness: true
  normal_gl: true
  normal_dx: true
  metalness: true
  opacity: true
  ambient_occlusion: true
  displacement: true
  cover: true